linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - gosec
  disable:
    - lll
    - gocyclo

run:
  timeout: 5m

issues:
  exclude-rules:
    - path: ".*\\.go"
      linters:
        - errcheck
      text: "error returned from"

