name: Linter

on:
    push:
        branches:
            - dev
    pull_request:
        branches:
            - dev

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: 1.23.1

            - name: Run golangci-lint
              uses: golangci/golangci-lint-action@v3
              with:
                  version: v1.54.2
                  args: "--timeout 5m"

